name: Creative Auto Commit Bot 🤖

on:
  schedule:
    - cron: "30 3 * * *"  # Every day at 9 AM UTC
  workflow_dispatch:     # Manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run creative commit script
        run: |
          python3 bot.py

      - name: Push changes
        run: |
          git config user.name "Yash"
          git config user.email "yashjoshi4755@gmail.com "
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "$(< .commit-msg)"
          git push
